### ISSUE TITLE
Option to hide extension of a file

### ISSUE THREAD

**Issue by sindresorhus** [LinusU/node-appdmg#96] opened 2016-05-12 15:08 UTC
I have `Show all filename extensions` set in the Finder preferences. Would be nice if the file extensions could be forcefully hidden in the DMG.

Seems to be possible as [`create-dmg`](https://github.com/andreyvit/create-dmg) has an option for it:

> --hide-extension [file name]: hide the extension of file

**Comment by cstruct** [comment] 2016-05-15 16:36
That option does not work on OS X 10.11.4.

[create-dmg](https://github.com/andreyvit/create-dmg/blob/master/create-dmg#L90) uses `set extension hidden` from AppleScript which does not work.
`SetFile -a E <file>` from [SetFile(1)](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/SetFile.1.html) does not seem to do the trick either.

Closing this. I can reopen if you have any other idea how to implement this.

**Comment by sindresorhus** [comment] 2016-05-15 16:41
I think I have an idea for this. According to https://github.com/LinusU/node-appdmg/pull/67, it's possible to set a custom title, since it's symlinked, so couldn't we just remove the extension from the title if this option is set?

**Comment by cstruct** [comment] 2016-05-15 17:03
Did some testing and that seems like a viable solution.

Reopening.

**Comment by LinusU** [comment] 2016-05-15 17:33
I don't understand, #67 only modifies the name of the file inside the image. If we remove the extension from that, we'll also remove the extension from the actual file, potentially rendering it broken?

**Comment by cstruct** [comment] 2016-05-15 17:44
I think I jumped the gun here. Did some more testing, removing the `.app` extension makes it a normal folder, all application semantics are lost.

**Comment by LinusU** [comment] 2016-05-15 17:55
This is actually a duplicate of #36 which also got closed without a solution...

Closing this for now, but I'll be happy to reopen if any solution comes to light 👌

**Comment by sindresorhus** [comment] 2016-05-15 17:56
Oh right. I was thinking aliases, but you're right, will not work with symlinks...

**Closed by LinusU** 2016-05-15 17:55 UTC

**Comment by LinusU** [comment] 2016-05-15 18:02
@sindresorhus Actually, which part is it that you wan't to hide? The `.app` on the actual app that's included?

I'm open to switching between symlinks and aliases

**Comment by sindresorhus** [comment] 2016-05-15 18:16
> The .app on the actual app that's included?

Yes

> I'm open to switching between symlinks and aliases

I wouldn't use aliases as they add an alias badge on the icon.

**Comment by LinusU** [comment] 2016-05-15 18:40
The app is neither a symlink nor an alias though, it's just a folder with the `.app` extension, so switching between them wouldn't help anything...

> I wouldn't use aliases as they add an alias badge on the icon.

👍
