### ISSUE TITLE
Icon and background are present in dmg, but not appearing when dmg is mounted

### ISSUE THREAD

**Issue by geekytime** [LinusU/node-appdmg#84] opened 2016-02-11 21:56 UTC
Here's what my app looks like in the finder before I bundle it in the dmg:

<img width="306" alt="screen shot 2016-02-11 at 3 51 04 pm" src="https://cloud.githubusercontent.com/assets/650247/12991968/5488c82a-d0d7-11e5-87ae-8b6d8d5f3f97.png">

Here's what my dmg looks like when I mount it:

<img width="885" alt="screen shot 2016-02-11 at 3 54 27 pm" src="https://cloud.githubusercontent.com/assets/650247/12992046/c92872a2-d0d7-11e5-9b68-59345453f3eb.png">

The size of the background is about right, and the file exist inside the dmg, but that's not how it looked the last time I used appdmg. :smile_cat: 

I'm also not sure how it could destroy my app's icon like that...

**Comment by geekytime** [comment] 2016-02-11 21:57
Here's my background image:
<img width="432" alt="installer-background" src="https://cloud.githubusercontent.com/assets/650247/12992090/0357d9d6-d0d8-11e5-8645-fb396ed4460f.png">

And my icon:
[netpegs-logo.icns.zip](https://github.com/LinusU/node-appdmg/files/127173/netpegs-logo.icns.zip)

And my config file:
```
{
  "title": "NetPegs",
  "icon": "netpegs-logo.icns",
  "background": "installer-background.png",
  "icon-size": 128,

  "contents": [
    { "x": 318, "y": 200, "type": "file", "path": "./Builds/OSX/NetPegs.app" },
    { "x": 595, "y": 200, "type": "link", "path": "/Applications" }
  ]
}
```

**Comment by geekytime** [comment] 2016-02-11 21:58
Anyone have any obvious thoughts or suggestions before I start diving into source code. :frowning:

**Comment by LinusU** [comment] 2016-02-11 22:07
Could you start by cloning the repo and running the tests? That should help us locating the problem.

**Comment by geekytime** [comment] 2016-02-11 22:18
Here are the test results. Something certainly seems to be amiss:

```
Chriss-iMac:node-appdmg Chris$ npm run test

> appdmg@0.3.5 test /Users/Chris/dev/node-appdmg
> standard && mocha -b



  api
    1) creates an image from a modern specification


  0 passing (14s)
  1 failing

  1) api creates an image from a modern specification:
     Error: Image looks visually incorrect
      at test/lib/visually-verify-image.js:31:10
      at node_modules/looks-same/index.js:129:13
      at node_modules/looks-same/index.js:67:13


```

**Comment by geekytime** [comment] 2016-02-11 22:20
Just for giggles, I uninstalled and reinstalled appdmg. I got some `error:` messages from xcode-select, but the install succeeded:

```
Chriss-iMac:node-appdmg Chris$ npm install -g appdmg@latest
/usr/local/bin/appdmg -> /usr/local/lib/node_modules/appdmg/bin/appdmg

> macos-alias@0.2.9 install /usr/local/lib/node_modules/appdmg/node_modules/macos-alias
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/volume/src/volume.o
  SOLINK_MODULE(target) Release/volume.node

> fs-xattr@0.1.11 install /usr/local/lib/node_modules/appdmg/node_modules/fs-xattr
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/xattr.node
/usr/local/lib
└─┬ appdmg@0.3.5
  ├── async@1.5.2
  ├─┬ ds-store@0.1.4
  │ ├─┬ bplist-creator@0.0.6
  │ │ └── stream-buffers@2.2.0
  │ ├── macos-alias@0.2.9
  │ └── unorm@1.3.3
  ├── fs-temp@1.0.0
  ├─┬ fs-xattr@0.1.11
  │ └── nan@2.2.0
  ├── image-size@0.3.5
  ├── minimist@1.2.0
  └── repeat-string@1.5.2
```

**Comment by pushtheworldllc** [comment] 2016-02-17 15:06
Pretty sure i am having the same issue over here! Installer background not showing on the dmg

**Comment by WWalmink** [comment] 2016-02-23 14:59
Same issue here. Everything else seems to work fine: no error, files in right location and window is the size of the background image.

Thanks in advance for your help!

**Comment by WWalmink** [comment] 2016-02-23 15:01
Okay, here's a clue: when I remove the @2x version from the folder, I will see the non-retina version of the background image fine.

**Comment by pushtheworldllc** [comment] 2016-02-23 15:02
Make sure to "eject" your old dmg's!!! That's what fixed this for me

**Comment by WWalmink** [comment] 2016-02-23 15:04
Thanks, that fixed it for me!

**Comment by pushtheworldllc** [comment] 2016-02-23 15:19
I know!! I couldn't believe that that was it! Glad to hear that worked for you :)

**Comment by jbleuzen** [comment] 2016-03-16 17:03
FYI, I had the exact same problem, background and icon were in the dmg, but when mounting I get the white icon drive and my background was not visible.

Unmounting all dmg and usb didn't work, the solution was to reboot my mac...
Yeah I know....

**Comment by leodie** [comment] 2016-04-15 08:36
Same issue here, but how could resolve that, I don't understand

**Comment by cstruct** [comment] 2016-05-22 19:18
Closing this as duplicate of #40

**Closed by cstruct** 2016-05-22 19:18 UTC

**Comment by george-hall-ucl** [comment] 2023-08-18 15:53
> Make sure to "eject" your old dmg's!!! That's what fixed this for me

In case this helps others: I found that sometimes old dmgs can still be mounted but not shown in Finder (I think due to botched builds?). These can be unmounted in Disk Utility, finally letting the background update. I guess this is why a restart sometimes appears to be needed to fix this issue, as it unmounts these "hidden" dmgs. Unmounting them in Disk Utility avoids the need to restart.
