### ISSUE TITLE
The 'openfolder' is not supported on Apple Silicon devices.

### ISSUE THREAD

**Issue by raghavnaphade** [LinusU/node-appdmg#219] opened 2022-12-23 08:49 UTC

**Comment by pzhlkj6612** [comment] 2022-12-23 13:27
Please see #216 and #218 .

**Comment by ngudbhav** [comment] 2023-01-22 06:15
This is occuring on Mac OS Ventura 13.1

**Comment by LinusU** [comment] 2023-02-01 04:49
duplicate of #218

**Closed by LinusU** 2023-02-01 04:49 UTC
