### ISSUE TITLE
Icon is not updated after generating the dmg file

### ISSUE THREAD

**Issue by adrianmg** [LinusU/node-appdmg#91] opened 2016-03-26 03:07 UTC
Hey, guys! I've double checked that the path for the final icon of the dmg file is correct, also I don't get any errors but for some reason, it's not working:

![image](https://cloud.githubusercontent.com/assets/589285/14057687/035332f6-f300-11e5-98d8-c6f23266fd80.png)

Sharing some screenshots:

![image](https://cloud.githubusercontent.com/assets/589285/14057674/a6ac965a-f2ff-11e5-89cd-5e74bfe13ca2.png)

![image](https://cloud.githubusercontent.com/assets/589285/14057677/ca9cb00e-f2ff-11e5-92f3-369b513088a2.png)

![image](https://cloud.githubusercontent.com/assets/589285/14057678/d189c870-f2ff-11e5-9653-a01cd187cfbe.png)

Any ideas?

**Comment by tanstry** [comment] 2016-04-21 16:43
Hey guys,

I met exactly the same issue, no icon appears on the dmg file.
The icon path is correct as we can see the small icon in the title window when mounting the dmg.

Anything special to respect in the icns file or something?

**Comment by grrrian** [comment] 2016-04-29 14:43
same issue here

**Comment by grrrian** [comment] 2016-04-29 16:26
The problem seems to happen when an icon is already specified in the app's Info.plist. This plugin does not overwrite it :(

**Comment by adrianmg** [comment] 2016-05-01 23:38
This is not a fix for the current project but at least a way to update the icon of your final DMG file, you just need to invoke this .sh file after generating the dmg. I'm using it as part of the Grunt flow, hope it helps!

https://gist.github.com/adrianmg/0d2e118a624847755dae

**Comment by LinusU** [comment] 2016-05-15 15:35
The `icon` setting only sets the icon of the window when the dmg is opened. It would be nice to support setting icon of the dmg as well though...

![screen shot 2016-05-15 at 17 29 18](https://cloud.githubusercontent.com/assets/189580/15275125/5629c5b8-1ac3-11e6-83f5-3511b9575bb1.png)

**Comment by cstruct** [comment] 2016-05-22 19:14
Closing as this is not currently the intended behaviour.

**Closed by cstruct** 2016-05-22 19:14 UTC
